const ADD_NUMBER = "ADD_NUMBER";
const SUB_NUMBER = "SUB_NUMER";
const ADD_TODO = "ADD_TODO";
const DELETE_TODO = "DELETE_TODO";
const COMPLETE_TODO = "COMPLETE_TODO";

export { ADD_NUMBER, SUB_NUMBER, ADD_TODO, DELETE_TODO, COMPLETE_TODO };
